module.exports = [
  "Linux",
  "Unix",
  "Javascript",
  "Algorithm",
  "Data Structure",
  "Big O Notation",
  "Recursion",
  "Object-Oriented Programming",
  "Abstraction",
  "Polymorphism",
  "Inheritance",
  "Encapsulation",
  "Binary Search",
  "Hashing",
  "Linked List",
  "Stack",
  "Queue",
  "Tree",
  "Graph",
  "Heap",
  "Sorting",
  "Searching",
  "Dynamic Programming",
  "Bit Manipulation",
  "Concurrency",
  "Parallelism",
  "Database",
  "SQL",
  "NoSQL",
  "API",
  "REST",
  "JSON",
  "HTTP",
  "HTTPS",
  "DNS",
  "TCP",
  "UDP",
  "IPv4",
  "IPv6",
  "Middleware",
  "Virtualization",
  "Containerization",
  "Microservices",
  "Security",
  "Encryption",
  "Authentication",
  "Authorization",
  "Cybersecurity",
  "Firewall",
  "Cryptography",
  "Machine Learning",
  "Artificial Intelligence",
  "Neural Network",
  "Deep Learning",
  "Natural Language Processing",
  "Reinforcement Learning",
  "Cloud Computing",
  "IaaS",
  "PaaS",
  "SaaS",
  "DevOps",
  "Continuous Integration",
  "Continuous Deployment",
  "Version Control",
  "Git",
  "Agile",
  "Scrum",
  "Kanban",
  "UML",
  "Software Development Lifecycle",
  "Debugging",
  "Testing",
  "Unit Testing",
  "Integration Testing",
  "Regression Testing",
  "User Interface",
  "User Experience",
  "Responsive Design",
  "Frontend",
  "Backend",
  "Full Stack",
  "API Gateway",
  "Load Balancing",
  "Serverless",
  "Lambda Function",
  "Docker",
  "Kubernetes",
  "Virtual Machine",
  "IDE",
  "CLI",
  "GUI",
  "Compilers",
  "Interpreters",
  "Memory Management",
  "File System",
  "Operating System",
  "Kernel",
  "Multithreading",
  "Deadlock",
  "Race Condition",
  "Semaphore",
  "Mutex",
  "Cache",
  "CPU Architecture",
  "Binary",
  "Hexadecimal",
  "Floating-Point",
  "Endianess",
  "TCP/IP",
  "VPN",
  "Latency",
  "Throughput",
  "Bandwidth",
  "Blockchain",
  "Smart Contract",
  "Cryptocurrency",
  "Quantum Computing",
].map((keyword) => keyword.toLowerCase());
